language: c

sudo: false

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev	
    - r-recommended
    - unixodbc-dev
    - libcurl4-openssl-dev

cache:
  directories:
    - ~/Rlib
    - $HOME/bin

before_install:
  - export PATH=$HOME/bin:$HOME/texlive/bin/x86_64-linux:$PATH
  - chmod 755 .push_gh_pages.sh
  - chmod 755 ghgenerate.R

install:
  - mkdir -p ~/Rlib
  - mkdir -p $HOME/bin
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - "wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash"
  - Rscript -e 'if(!require(devtools)) { install.packages("devtools", dependencies = TRUE) }'
  - Rscript -e 'update.packages(ask = FALSE, instlib = "~/Rlib")'
  - Rscript -e 'devtools::install_github("rstudio/rmarkdown")'

script:
  - ./.push_gh_pages.sh
