## ---- setup                       --------------
source("genericprep.R")
## ---- barchart                    --------------
## ---- aggbarchart                 --------------
## ---- groupedbarchart             --------------
## ---- scatterplot                 --------------
## ---- scatterplotcircles          --------------
## ---- binnedscatterplot           --------------
## ---- colouredscatterplot         --------------
## ---- colouredtextscatterplot     --------------
## ---- bubblechart                 --------------
## ---- scatterplotlogscale         --------------
## ---- linechart                   --------------
## ---- multiserieslinechart        --------------
## ---- histogram                   --------------
## ---- areachart                   --------------
## ---- boxplot                     --------------
## ---- stackedbar                  --------------
## ---- horizstackedbar             --------------
## ---- normalisedstackedbar        --------------
## ---- stackedarea                 --------------
## ---- normalisedstackedarea      --------------
## ---- layeredbar                  --------------
## ---- trellisbar                  --------------
## ---- trellisstackedbar           --------------
## ---- trellisscatter              --------------
## ---- trellishistogram            --------------
## ---- trelliscolouredscatterplot  --------------
## ---- steamgraph                  --------------
## ---- networkgraph                --------------
## ---- beechart                    --------------
## ---- stripplot                   --------------
## ---- slopegraph                  --------------

